import { Food } from './app/shared/models/Food';
export const sampleFoods: Food[] = [
  {
    id: '1',
    name: 'Vegetable Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: './assets/food-1.jpg',
    tags: ['FastFood', 'Lunch'],
  },
  {
    id: '2',
    name: 'Vegetable Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: true,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: './assets/food-1.jpg',
    tags: ['FastFood', 'Lunch'],
  },
  {
    id: '3',
    name: 'Vegetable Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: './assets/food-1.jpg',
    tags: ['FastFood', 'Lunch'],
  },
  {
    id: '4',
    name: 'Vegetable Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: './assets/food-1.jpg',
    tags: ['FastFood', 'Lunch'],
  },
  {
    id: '5',
    name: 'hamburger',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: './assets/food-1.jpg',
    tags: ['FastFood', 'Lunch'],
  },
];
